include ../Makedefs

objects =             \
	main.o  	      \
	Collectibletile.o \
	Event.o    	  	  \
	Game.o 		  	  \
	GameLoop.o 	  	  \
	Map.o 		  	  \
	Tile.o        	  \
	Tileset.o     	  \
	Video.o 	  	  \

headers = 
	$(INCLUDE_DIR)/Collectibletile.h   \ 
	$(INCLUDE_DIR)/Event.h             \
	$(INCLUDE_DIR)/Game.h              \
	$(INCLUDE_DIR)/GameLoop.h          \
	$(INCLUDE_DIR)/Harvest.h           \
	$(INCLUDE_DIR)/Map.h               \
	$(INCLUDE_DIR)/Tile.h              \
	$(INCLUDE_DIR)/Tileset.h           \
	$(INCLUDE_DIR)/Video.h             \

